[package]
name = "higgins"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
arrow = "55.0.0"
easy-repl = "0.2.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1.41"
