[workspace]
resolver = "3"
members = [
    "higgins-cli",
    "higgins-client",
    "higgins-codec",
    "higgins-core",
    "higgins-functions",
    "higgins-functions/tests/example_wasm"
, "higgins-shared", "higgins-tests"]
exclude = ["higgins-functions/tests/example_wasm"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = { version = "2" }
tracing = "0.1"
clap = { version = "4", features = ["derive"] }
arrow = { version = "55", features = ["ffi"] }
arrow-schema = { version = "55", features = ["serde"] }
arrow-json = "55"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.9.5"
rkyv = "0.8.10"
prost = { version = "0.13" }

[profile.release-with-debug]
inherits = "release"
debug = true
