[package]
name = "higgins-codec"
version = "0.1.3"
edition = "2024"

[dependencies]
prost = "0.13.5"
tokio = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = "0.13.5"
