name: Check PR

on:
  pull_request:
    branches:
      - "main"

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  fmt:
    if: github.event.pull_request.draft == false
    name: "Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Run Format
        run: cargo fmt --check
  clippy_check:
    if: github.event.pull_request.draft == false
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  test:
    if: github.event.pull_request.draft == false
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Test
        run: cargo test
  deny:
    if: github.event.pull_request.draft == false
    name: "Cargo Deny"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
  # miri:
  #   name: "Miri"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Protoc
  #       uses: arduino/setup-protoc@v3
  #     - name: Install Miri
  #       run: |
  #         rustup toolchain install nightly --component miri
  #         rustup override set nightly
  #         cargo miri setup
  #     - name: Test with Miri
  #       run: cargo miri test
