[package]
name = "higgins-shared"
version = "0.1.0"
edition = "2024"
license-file = "../LICENSE.md"

[dependencies]
thiserror = {workspace = true}
arrow = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
toml = { workspace = true }
rkyv = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
